config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments

  resources :users, only: [:index] do
    member do
      get :posts
    end
    collection do
      get :authors
    end
  end

  resources :followings, only: [:destroy]  do
    member do
      get :follow
    end
  end

  resources :posts
  resources :comments
  root 'posts#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

end

app/models/followings.rb
class Followings < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, class_name: 'User'

  validates :user_id, presence: true
  validates :follower_id, presence: true
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: [:show, :edit, :update, :destroy]

  # GET /followings
  # GET /followings.json
  def index
    @following = current_user.following.count
    @followers = current_user.followers.count
  end

  def follow
    #@following = Following.new(following_params)
    @following = current_user.following.create user_id: params[:id]
    Blogmail.send_email(User.find(params[:id]).email,current_user.email).deliver
    @author_id = params[:id]
    #@action = 'follow'
    @notice = 'success'

  end

  # DELETE /followings/1
  # DELETE /followings/1.json
  def destroy
    @author_id = @following.user_id
    @following.destroy

    #@current_user.following.where(user_id: params[:user_id]).first.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following
      @following = Followings.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params[:following]
    end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_following_link.html.slim
-if is_following?(@author_id)
  = link_to 'unfollow', following_path(@following.id) , method: :delete, remote: :true
-else
  = link_to 'follow', follow_following_path(@author_id), remote: :true

app/views/followings/_form.html.slim
= simple_form_for(@following) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/followings/destroy.js.erb
$("<%= "#div#{@author_id}"%>").html("<%= j render partial: 'followings/following_link' %>");

app/views/followings/edit.html.slim
h1 Editing following

== render 'form'

= link_to 'Show', @following
'|
= link_to 'Back', followings_path

app/views/followings/follow.js.erb
$("<%= "#div#{@author_id}"%>").html("<%= j render partial: 'followings/following_link' %>");

app/views/followings/index.html.slim
h1 Listing followings

table
  thead
    tr
      th
      th
      th

  tbody
    - @followings.each do |following|
      tr
        td = link_to 'Show', following
        td = link_to 'Edit', edit_following_path(following)
        td = link_to 'Destroy', following, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Following', new_following_path

app/views/followings/new.html.slim
h1 New following

== render 'form'

= link_to 'Back', followings_path

app/views/followings/show.html.slim
p#notice = notice


= link_to 'Edit', edit_following_path(@following)
'|
= link_to 'Back', followings_path