config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments

  resources :users, only: [:index] do
    member do
      get :posts
    end
    collection do
      get :authors
    end
  end

  resources :followings, only: [:destroy]  do
    member do
      get :follow
    end
  end

  resources :posts
  resources :comments
  root 'posts#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    #byebug
    @post = Post.find(params[:post_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    #byebug
    respond_to do |format|
      if current_user
        format.js {
            @comment = current_user.comments.create(comment_params)
        }

      end
    end
  end

  #   respond_to do |format|
  #     if @comment.save
  #       format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
  #       format.json { render :show, status: :created, location: @comment }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render 'comments/update' }
      else
        #format.js { render :edit , notice: @comment.errors }
        format.js { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment_id = @comment.id
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.js { render 'comments/destroy', status: :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def author_by_id(user_id)
    User.email_finding(user_id)   #returns email of comment author
  end
end

app/views/comments/_comment.html.slim
td
  p
    '
    = author_by_id(@comment.user_id)
    ' :
    = @comment.comment
td
    = link_to 'Edit', edit_comment_path(@comment.id), remote: :true
    |---
    = link_to 'Delete', comment_url(@comment.id), method: :delete, remote: :true, data: { no_turbolink: true ,confirm: 'Are you certain you want to delete this?' }

app/views/comments/_form.html.slim
= simple_form_for @comment, remote: true do |f|
    = f.error_notification

    .form-inputs
        = f.input :comment
        - if @post
            = f.input :post_id, :as => :hidden, :input_html => { :value => @post.id }

    .form-actions
        = f.button :submit

app/views/comments/create.js.erb
$('#comments_list tbody').append("<tr></tr>");
$('#comments_list tbody tr:last-of-type').attr("id","<%= "tr_#{@comment.id}"  %>");
$('#comments_list tbody tr:last-of-type').append('<%= j render 'comments/comment'%>');

app/views/comments/destroy.js.erb
$("<%="#tr_#{@comment_id.to_s}"%>").remove();

app/views/comments/edit.js.erb
$("#div_comment").html('<%= j render partial: 'form' %>');
$("#MyFancyLink").fancybox().trigger('click');

$(".edit_comment").submit(function() {
    $.fancybox.close();
});

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

=# link_to 'Back', comments_path

app/views/comments/new.js.erb
$("#div_comment").html("<%= j render 'comments/form' %>");
$("#MyFancyLink").fancybox().trigger('click');

$("#new_comment").submit(function() {
    $.fancybox.close();
});

app/views/comments/show.html.slim
p#notice = notice


= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path

app/views/comments/update.js.erb
$("<%= '#tr_'+@comment.id.to_s %>").html('<%= j render 'comments/comment'%>');