config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments

  resources :users, only: [:index] do
    member do
      get :posts
    end
    collection do
      get :authors
    end
  end

  resources :followings, only: [:destroy]  do
    member do
      get :follow
    end
  end

  resources :posts
  resources :comments
  root 'posts#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :post
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
    respond_to do |format|
      format.js { render partial: 'post_attachments/editjs' }
      end
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment.post, notice: 'Post attachment was successfully updated.' }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post_attachment.post_id), notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :avatar)
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_editjs.js.erb
$("#modal-window").html("<%= j render template: 'post_attachments/edit.html.slim' %>");
//$("#modal-window").show();
//$("#modal-window").attr('class','modal.fade');
//alert('sasas');

$("#modal-window").on('hidden.bs.modal', function () {
    $("#modal-window").html('');
})

app/views/post_attachments/_form.html.slim
= image_tag @post_attachment.avatar
= simple_form_for(@post_attachment) do |f|
  = f.error_notification
  .form-inputs
    = f.label :avatar
    = f.file_field :avatar
  .form-actions
    = f.button :submit

app/views/post_attachments/edit.html.slim
.col-md-6.centre.modal-content
  h1 Edit Post attachments

  = render 'form'

  /= link_to 'Show', @post_attachment
  /'|
  = link_to 'Delete', post_attachment_path(@post_attachment.id), method: :delete

app/views/post_attachments/index.html.slim
h1 Listing post_attachments

table
  thead
    tr
      th Post
      th Avatar
      th
      th
      th

  tbody
    - @post_attachments.each do |post_attachment|
      tr
        td = post_attachment.post_id
        td = post_attachment.avatar
        td = link_to 'Show', post_attachment
        td = link_to 'Edit', edit_post_attachment_path(post_attachment)
        td = link_to 'Destroy', post_attachment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Post attachment', new_post_attachment_path

app/views/post_attachments/new.html.slim
h1 New post_attachment

== render 'form'

= link_to 'Back', post_attachments_path

app/views/post_attachments/show.html.slim
p#notice = notice

p
  strong Post:
  = @post_attachment.post_id
p
  strong Avatar:
  = @post_attachment.avatar

= link_to 'Edit Attachment', edit_post_attachment_path(@post_attachment),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}
'|
= link_to 'Back', post_attachments_path