config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments

  resources :users, only: [:index] do
    member do
      get :posts
    end
    collection do
      get :authors
    end
  end

  resources :followings, only: [:destroy]  do
    member do
      get :follow
    end
  end

  resources :posts
  resources :comments
  root 'posts#index'

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_attachments

  accepts_nested_attributes_for :post_attachments
  #mount_uploaders :avatars, AvatarUploader

  acts_as_paranoid

  belongs_to :user
  has_many :comments, dependent: :destroy

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments

    @author = User.find(@post.user_id).email
    @post_attachments = @post.post_attachments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        unless params[:post_attachments].blank?
          params[:post_attachments]['avatar'].each do |a|
            @post_attachment = @post.post_attachments.create!(:avatar => a)
          end
        end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        params[:post_attachments]['avatar'].each do |a|
          @post_attachment = @post.post_attachments.create!(:avatar => a)
        end
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id,post_attachments_attributes: [:id, :post_id, :avatar])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
/= simple_form_for(@post) do |f|
/  = f.error_notification
/
/  .form-inputs
/    = f.input :title
/    = f.input :body
/      - @post.avatars.each do |avatar|
/        = image_tag avatar.url, class: 'img-responsive'
/        - #f.hidden_field(:avatars_cache)
/        = f.file_field(:avatar)
/    -# f.file_field :avatars, multiple: true
/
/  .form-actions
/    = f.button :submit

= simple_form_for(@post, :input_html  => { :multipart => true }) do |f|
  .form-inputs
    = f.input :title
    = f.input :body
    = f.file_field :avatar, :multiple => true, name: 'post_attachments[avatar][]'
  .actions
    = f.button :submit

  -@post.persisted?
    -@post.post_attachments.each do |avatar|
      = image_tag avatar.avatar_url
      /= link_to 'Edit Attachment', edit_post_attachment_path(avatar)
      = link_to 'Edit Attachment', edit_post_attachment_path(avatar),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back to posts', posts_path

app/views/posts/index.html.slim
h1 Listing posts



.col-md-8.centre
  row#post_container

    - @posts.each do |p|
      .col-md-12#post_header
        p
          |
          h3
            span.glyphicon.glyphicon-bullhorn.glyphcss
            |
            = p.title
          p.tagline
            span#name_span
              |
              ="by "+author_by_id(p.user_id)+" at "
            |
            =p.created_at
      .col-md-12
        .row
          .post_div.col-md-12


            .col-md-10#post_body
              p#post_textarea
                =p.body
              - p.post_attachments.each do |avatar|
                = image_tag avatar.avatar_url,class: 'img-responsive'
                /= link_to 'Edit Attachment', edit_post_attachment_path(avatar)
                = link_to 'Edit Attachment', edit_post_attachment_path(avatar),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}
              p
                =link_to 'Show', p
                -if can? :update, p
                  |
                  = link_to 'Edit', edit_post_path(p)
                -if can? :destroy, p
                  |
                  = link_to 'Destroy', p, data: {:confirm => 'Are you sure?'}, :method => :delete






= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice
table
  tr
    td
      p
        strong Title:
        = @post.title
  tr
    td
      p
        strong Body:
        = @post.body
      p
        strong Author:
        = @author

-@post_attachments.each do |p|
  = image_tag p.avatar_url
  = link_to 'Edit Attachment', edit_post_attachment_path(p)

ruby:
  def row_id(comment_id)
    {tag: 'tr', id: 'tr_'+ comment_id.to_s }
  end
#comments_div
  h2 Comments
  table#comments_list.table
    thead
    tbody
      - @comments.each do |c|
        *row_id(c.id)
          /* calling method row_id to insert IDs to each row(see line nmbr 16  starting with ruby:)
          td
            p
              '
              =author_by_id(c.user_id)
              ' :
              '
              = c.comment
          td
            = link_to 'Edit', edit_comment_path(c.id), remote: :true
            |---
            = link_to 'Delete', comment_url(c.id), method: :delete, remote: :true, data: { no_turbolink: true ,confirm: 'Are you certain you want to delete this?' }
'|


= link_to 'Edit Post', edit_post_path(@post)
'|
= link_to 'Back', posts_path
'|
= link_to 'Comment', new_comment_path(post_id: @post.id),  remote: :true , id: 'btnForm'
'|
= link_to '', "#div_comment", id: 'MyFancyLink'



#div_comment

javascript:
    $(document).ready(function () {
        //$("#MyFancyLink").fancybox();
    });